### ISSUE TITLE
Questions about Requirements of Environments

### ISSUE THREAD

**Issue by Baxkiller** [lileipisces/PEPLER#5]
I installed `Python=3.6` and `torch=1.6` according to the required dependencies you mentioned, but when I installed transformers using the command `conda install transformers=4.18.0`, the following problem occurred:

```shell
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - transformers=4.18.0 -> python[version='>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python=3.6
```

So I would like to confirm with you the dependency packages required to run this project.

**Comment by lileipisces** [comment]
I ran the program with Python 3.6.9. Maybe you can upgrade Python to 3.7 as instructed by the error message. I recently encountered the exactly same problem when running other programs.

**Comment by Baxkiller** [comment]
Yeah. I have solved the problem by upgrading Python version and it runs well.
Thanks to your helpful reply.
